validações do cadastrio autor
laiscavalcanti/e-Digi pull request #1
Opened 2020-06-16 00:52 UTC by laiscavalcanti

@wandersonmaceds 

Oi, Wands :} Primeiramente, desculpa pela falta de entendimento do projeto no sentido técnico. Eu tava com uma mistura de medo e ansiedade diante dele. Mas acredito que encontrei o caminho (Jonilson me ajudou nesse processo).

2020-06-16 17:02 UTC, wandersonmaceds requested changes

2020-06-16 17:02 UTC, wandersonmaceds commented on app/models/Author.js
> +    if (!valueNotEmpty(name))
Não fica confusa a leitura do não, não vazio? Aqui, por falta de expressividade no código, você pode acabar com má interpretação e gerando falsos positivos: a negação do sinal, faz a negação no nome da função se transformar em uma afirmação, ou seja, uma função chamada `eh_vazio` seria mais expressivo e não deixaria dúvidas.

2020-06-16 17:02 UTC, wandersonmaceds commented on app/models/validate.js
> +export const mailFormat = /^([\w-]\.?)+@([\w-]+\.)+([A-Za-z]{2,4})+$/g;
Por que um arquivo de validações estaria no mesmo diretório dos modelos?

2020-06-16 17:02 UTC, wandersonmaceds commented on app/test/Author.js
> +}
Para cada teste, um try/catch diferente, fica difícil saber tudo que falhou, se na primeira falha, os demais testes não serão executados.

2020-06-16 17:02 UTC, wandersonmaceds commented on app/models/Author.js
> +    if (!valueNotEmpty(email) || !email.match(mailFormat))
Muitas negações.

2020-06-16 21:26 UTC, laiscavalcanti commented on app/models/validate.js
> +export const mailFormat = /^([\w-]\.?)+@([\w-]+\.)+([A-Za-z]{2,4})+$/g;
Seria uma pasta `helpers`? Por agora eu deixei dentro da `app`

2020-06-16 21:27 UTC, laiscavalcanti commented on app/models/Author.js
> +    if (!valueNotEmpty(name))
Sim, eu vou passar o que não precisa de negação, de fato ficou mais complexo.

2020-06-16 21:29 UTC, laiscavalcanti commented on app/dao/Author.js
> +  }
Eu removi os consoles. Eu criei outro método, em que primeiro faz a procura do email e no outro metodo faz a verificação para salvar e adicionar na lista. Mas não entendi, muito bem o uso das chaves: `Se eu passar {}, acontece o que`

2020-06-16 21:30 UTC, laiscavalcanti commented on app/test/Author.js
> +}
Refiz os testes, um try/catch para cada verificação.

2020-06-17 12:24 UTC, wandersonmaceds requested changes

2020-06-17 12:24 UTC, wandersonmaceds commented on app/models/Author.js
> +    if (isEmpty(name)) throw new Error(`O campo nome precisa ser preenchido`);
boa

2020-06-17 12:24 UTC, wandersonmaceds commented on app/dao/Author.js
>    }
Aqui nada mudou, você só moveu o problema de lugar, ainda não existe garantia de que se eu passar um objeto que não é um autor, se seu código vai alarmar isso ou vai dar os erros de undefined que não são fáceis de trackear depois que o projeto cresce e os fluxos ficam mais complexos.

2020-06-17 12:24 UTC, wandersonmaceds commented on app/models/Author.js
> +    if (isEmpty(name)) throw new Error(`O campo nome precisa ser preenchido`);
Se eu tentar passar null, o que acontece?

2020-06-26 17:26 UTC, wandersonmaceds requested changes

2020-06-29 23:54 UTC, wandersonmaceds requested changes

2020-07-06 13:33 UTC, wandersonmaceds approved these changes

2020-07-08 20:31 UTC, merged